### ISSUE TITLE
Building sbt-web plugins that depend on npm packages

### ISSUE THREAD

**Issue by onelson** [sbt/sbt-web#105]
I started working on a source task plugin for running ES6 code through the babel transpiler (https://github.com/onelson/sbt-babeljs) following @huntc's excellent sbt-stylus example, but ran into a snag... I'm not exactly sure how to get the node module into my plugin without building a webjar for it. I believe there *should* be a webjar for babel, but there isn't one currently and I don't yet know how best to build one without just putting in a request and waiting for it to be delivered by the webjar folks (which is a really lame way to do things - I'd rather learn how to help myself).

In the meantime, I'm looking for other ways to get the js into my plugin so that I can complete development, then later trade out for a webjar dependency once it becomes available.

According to the docs here, it looks as though I should be able to add a `package.json` to my project root and the packages should be available to my plugin at runtime. Unfortunately, this doesn't seem to be working for me and I fear I've missed a step somehow (scripted tests fail with `Error: Cannot find module 'babel-core'`). Docs suggest I also need to declare that my task depends on `nodeModules in Plugin` which I believe I have done (https://github.com/onelson/sbt-babeljs/blob/master/src/main/scala/com/theomn/sbt/babeljs/SbtBabelJS.scala#L56).

Anyway, I'm looking for some advice on how to proceed.

Cheers,
Owen

**Comment by jamesward** [comment]
We will get to creating the `babel-core` WebJar asap.  [Contributing the WebJar](http://www.webjars.org/contributing) speeds up the process.  Agree that the manual creation is not ideal, which is why we recently [launched the Bower WebJar sync](http://www.jamesward.com/2015/03/23/scaling-the-webjars-project-with-on-demand-bower-packages) and might be doing the same for NPM.

**Comment by huntc** [comment]
Thanks for replying @jamesward and apologies @onelson for my tardy response.

The package.json approach will only work for you during development of your plugin. We haven't got around to having npm packages at runtime, but given what James states, npm packages will likely come via WebJars so they'll be no need.

Take some inspiration from https://github.com/webjars/jshint on how to create node/web oriented webjars.

**Comment by onelson** [comment]
Oh dang, @jamesward! This contributing guide is just what I needed, I think. I missed this page on webjars.org (perhaps because it's styled as a button?)

What I was trying to say in our brief twitter exchange was that it felt wrong to just post the request and wait for someone else to do the manual labor, especially in this case when babel has such a phenomenally large set of dependencies all of it's own. I didn't mean to pressure anyone to build this webjar asap ;) 

The motivating factor for me to build the plugin in the first place was for me to understand the process completely so that I may never feel like I can't use a particular piece of front-end tech just because it's not provided by someone else! I believe this is the spirit of what you are trying to accomplish with sbt-web, webjars, etc. It's just taking me a little bit to piece all the info together, coming at this as a new-to-the-jvm guy. The ecosystem is still a bit foreign to me.

@huntc I'll dig into this webjar. Thanks for the pointer! FYI, I doubt I'd have been able to get as far as I have without watching your video on the stylus plugin. Very helpful resource!
