### ISSUE TITLE
Adding production ready assets to classpath breaks auto reload of css/js etc in development

### ISSUE THREAD

**Issue by sporritt** [sbt/sbt-web#109]
This suggestion from your readme:

```
To automatically add the production-ready assets to classpath, the following might be useful:

(managedClasspath in Runtime) += (packageBin in Assets).value
```

is indeed useful: with this line in `build.sbt` three things occur:
- the web assets are packaged into a jar
- the app jar's manifest gets a reference to the web assets jar, putting them onto the classpath.
- auto reloading while running in development no longer works.

So, two of these things are great, and the third is a bit problematic, but probably understandable given what the line of code asks the app to do. The problem applies to CSS files (in `app/assets/css` and being processed by `sbt-sass`) as well as anything inside `public` (presumably being processed by `sbt-web`).

It's entirely possible that my rudimentary understanding of SBT means there's something else I can say to override this, or to specify that it should not occur when running in development, or something else. I don't know.  Any suggestions you have would be appreciated.

**Comment by sporritt** [comment]
(I'm using Play 2.3.6, SBT 0.13, sbt-web 1.1.0, sbt-sass 0.1.9, scala 2.11.1)

**Comment by jroper** [comment]
That suggestion is for using sbt-web by itself, Play has its own sbt-web specific integration that doesn't require that configuration. And this is a Play issue anyway, not an sbt-web issue.
