### ISSUE TITLE
publishLocal

### ISSUE THREAD

**Issue by Houdini** [sbt/sbt-web#111]
publishLocal raises a lot of errors, like this:
/home/houdini/codes/sbt-web/src/main/scala/com/typesafe/sbt/web/pipeline/Pipeline.scala:25: can't expand macros compiled by previous versions of Scala

full log here: https://gist.github.com/Houdini/4b14599bb1beb32f88c6

Any ideas how to fix it?

Thanks

**Comment by Houdini** [comment]
By the way

> scalaVersion
[info] 2.11.6
> sbtVersion
[info] 0.13.8

**Comment by jroper** [comment]
I don't know why you're compiling against Scala 2.11.6, but no version of sbt-web has ever been compatible with Scala 2.11. Anyway works for me.
