### ISSUE TITLE
Incremental compilation file dependencies

### ISSUE THREAD

**Issue by irundaia** [sbt/sbt-web#127]
Hi,

I'm trying to write a plugin which compiles sass files. I'm adhering to the convention that files with names starting with an "_" are not compiled directly, but they can be included in other files. I attempted to do this by using the following file filter:
```scala 
excludeFilter in sassify := HiddenFileFilter || "_*"
```

The modified source files are then compiled as:
```scala
val results = incremental.syncIncremental((streams in Assets).value.cacheDirectory / "run", sources) {
  modifiedSources: Seq[File] =>
    if (modifiedSources)
      streams.value.log.info(s"Sass compiling on ${modifiedSources} source(s)")

    val compilationResults: Map[File, (OpResult, Seq[Problem])] = modifiedSources
      .map(inputFile =>
        inputFile -> doCompile(inputFile)
      ).toMap

    if (compilationResults.nonEmpty)
      streams.value.log.info(s"Sass compilation done. Compiled ${compilationResults.size} file(s).")

    (compilationResults.mapValues(_._1), compilationProblems.values.flatMap(_._2))
}
```

Note that when the doCompile function returns an OpSuccess, I make sure that any included file is included in the readFiles parameter.

Unfortunately, when one of the imported files (starting with an _) is changed, the including file is not recompiled. Any idea how I could fix this?

**Comment by huntc** [comment]
Did you see this? https://github.com/ShaggyYeti/sbt-sass

**Comment by irundaia** [comment]
I did, this compiler has the same issue as my implementation. Furthermore, my implementation does not rely on a command line version of sass (I'm not allowed to install it on my build server).

**Comment by irundaia** [comment]
Turns out, my compiler had an issue when reporting the file dependencies (it used erroneous paths). Now that I've resolved this issue, it works like a charm. Sorry for bothering you with this....

**Comment by huntc** [comment]
No probs. Thanks for the update.
