### ISSUE TITLE
PathMapping behaves inconsitent

### ISSUE THREAD

**Issue by magnusart** [sbt/sbt-web#128]
So after killing a few hours trying to find out why `sbt-concat` would not find certain files I found that `PathMapping` behavior is not consistent.

According to the documentation on SbtWeb git-page `PathMapping` should be a tuple of `(full path, relative path)`. Files under the `webTarget` have multiple sub directories in their relative path but not files from `assets` directories (generated from `sbt-closure`).

This inconsistency is very confusing, especially in my case where I have unminified files (webTarget) in dev and minified files (assets) in prod. This means I have to hack my relative paths depending if using `SNAPSHOT` or not.

**Comment by huntc** [comment]
This sounds like an issue for sbt-closure to solve. Can you please raise it there?
