### ISSUE TITLE
Make 'Exporting ...' debug?

### ISSUE THREAD

**Issue by schmitch** [sbt/sbt-web#142]
Hello currently in sbt-web 1.4.0 we have a new information Log here:
https://github.com/sbt/sbt-web/blob/master/src/main/scala/com/typesafe/sbt/web/SbtWeb.scala#L321

I just wanted to ask here first, could I create a PR that makes this debug? I mean I don't see any value here for adding this info log here.

**Comment by huntc** [comment]
Sure
