### ISSUE TITLE
sbt-web throws NPE multi project angular 2 non play build

### ISSUE THREAD

**Issue by ashugupt** [sbt/sbt-web#146]
On issuing a ~run command on project throws the following NPE(build.sbt) pasted towards end.

> compile
> [success] Total time: 0 s, completed Oct 8, 2016 3:46:16 AM
> run
> [trace] Stack trace suppressed: run last web/web-assets:webJarsNodeModules for the full output.
> [trace] Stack trace suppressed: run last web/web-assets:webJars for the full output.
> [error](web/web-assets:webJarsNodeModules) java.lang.NullPointerException
> [error](web/web-assets:webJars) java.lang.NullPointerException
> [error] Total time: 4 s, completed Oct 8, 2016 3:46:23 AM
> last web/web-assets:webJars
> java.lang.NullPointerException
>     at org.webjars.WebJarExtractor.getJsonNodeModuleId(WebJarExtractor.java:341)
>     at org.webjars.WebJarExtractor.findWebJarsInJarFile(WebJarExtractor.java:286)
>     at org.webjars.WebJarExtractor.extractWebJarsTo(WebJarExtractor.java:113)
>     at org.webjars.WebJarExtractor.extractAllWebJarsTo(WebJarExtractor.java:61)
>     at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateWebJars$1.apply(SbtWeb.scala:434)
>     at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateWebJars$1.apply(SbtWeb.scala:433)
>     at com.typesafe.sbt.web.SbtWeb$.withWebJarExtractor(SbtWeb.scala:419)
>     at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$generateWebJars(SbtWeb.scala:432)
>     at com.typesafe.sbt.web.SbtWeb$$anonfun$27.apply(SbtWeb.scala:274)
>     at com.typesafe.sbt.web.SbtWeb$$anonfun$27.apply(SbtWeb.scala:274)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>     at sbt.std.Transform$$anon$4.work(System.scala:63)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>     at sbt.Execute.work(Execute.scala:237)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> [error](web/web-assets:webJars) java.lang.NullPointerException

---

build.sbt

import com.scalapenos.sbt.prompt.SbtPrompt.autoImport._
import sbt.Keys._

lazy val commonSettings = Vector(
  organization := "xxxxxxxxxxx",
  version := "0.0.1-SNAPSHOT",
  scalaVersion := "2.11.8",

  resolvers ++= Seq(
    Opts.resolver.mavenLocalFile,
    "Confluent" at "http://packages.confluent.io/maven"
  ),

  incOptions := incOptions.value.withNameHashing(true),
  updateOptions := updateOptions.value.withCachedResolution(cachedResoluton = true),

  promptTheme := com.scalapenos.sbt.prompt.PromptThemes.ScalapenosTheme
)

lazy val root =
  (project in file("."))
    .enablePlugins(GitVersioning, JavaAppPackaging)
    .settings(name := "xxxxxxx")
    .settings(commonSettings: __)
    .settings(compilationSettings: __)

lazy val app =
  (project in file("app"))
    .enablePlugins(GitVersioning, JavaAppPackaging)
    .settings(name := "xxxxxxx-app")
    .settings(commonSettings: __)
    .settings(compilationSettings: __)
    .settings(
      libraryDependencies ++= commonLibs
    )
    .settings(
      excludeDependencies ++= Vector(
        "org.slf4j" % "slf4j-nop",
        "org.slf4j" % "slf4j-simple"
      )
    )

lazy val web =
  (project in file("web"))
    .enablePlugins(GitVersioning, JavaAppPackaging, SbtWeb)
    .settings(name := "xxxxxx-web")
    .settings(commonSettings: __)
    .settings(compilationSettings: __)
    .settings(projectAddOns.settings)
    .settings(
      // the typescript typing information is by convention in the typings directory
      // It provides ES6 implementations. This is required when compiling to ES5.
      typingsFile := Some(baseDirectory.value / "typings" / "browser.d.ts"),

```
  // use the webjars npm directory (target/web/node_modules ) for resolution of module imports of angular2/core etc
  resolveFromWebjarsNodeModulesDir := true,

  // use the combined tslint and eslint rules plus ng2 lint rules
  (rulesDirectories in tslint) := Some(List(tslintEslintRulesDir.value, ng2LintRulesDir.value)),

  // If true, sources from the project's base directory are included as main sources.
  sourcesInBase := false,

  // adds the assets resulting from the assets pipeline to the classpath.  // TODO avoid the webjar generated for export be included in the class path.
  (managedClasspath in Runtime) += WebKeys.assets.in(Assets).value,
  // alternatively, you can use the jar version of the assets.
  //(managedClasspath in Runtime) += (packageBin in Assets).value

  // adds, to the runtime classpath, the directories where the webjars are extracted (with META-INF and version stripped).
  (managedClasspath in Runtime) ++= WebKeys.nodeModuleDirectories.in(Assets).value,
  (managedClasspath in Runtime) += WebKeys.webJarsDirectory.in(Assets).value,

  // run the application in a separate JVM (instead of using the same than SBT)
  fork in run := true
)
.settings(
  libraryDependencies ++= webLibs
)
.settings(
  dependencyOverrides += WebDeps.minimatch
)
```

lazy val commonLibs = Vector(
  Dependencies.slf4j,
  Dependencies.scalaLogging,
  Dependencies.logback,

  Dependencies.circeCore,
  Dependencies.circeGeneric,
  Dependencies.circeParser,

  Dependencies.http4sDsl,
  Dependencies.http4sServer,
  Dependencies.http4sClient,

  Dependencies.scalaCheck,
  Dependencies.scalaTest
)

lazy val webLibs = Vector(
  WebDeps.ngCommon,
  WebDeps.ngCompiler,
  WebDeps.ngCore,
  WebDeps.ngPlatformBrowserDynamic,
  WebDeps.ngPlatformBrowser,

  WebDeps.systemJs,

  WebDeps.rxJs,

  WebDeps.es6Promise,
  WebDeps.es6Shim,

  WebDeps.reflectMetadata,

  WebDeps.coreJs,
  WebDeps.zoneJs,

  WebDeps.bootstrap,
  WebDeps.ngBootstrap,

  WebDeps.symbolObservable,

  WebDeps.typescript,
  WebDeps.tslintEsLint,

  WebDeps.codelyzer,

  WebDeps.jasmine
)

lazy val compilationSettings = Vector(
  // compile settings
  compileOrder := CompileOrder.Mixed,

  // javac settings
  javacOptions ++= Vector(
    "-g:none",
    "-source", "1.8",
    "-target", "1.8",
    "-Xlint"
  ),

  // scalac settings
  scalacOptions ++= Vector(
    "-unchecked",
    "-feature",
    "-deprecation",
    "-language:implicitConversions",
    "-language:higherKinds",
    "-language:existentials",
    "-language:postfixOps",
    "-target:jvm-1.8",
    "-encoding", "UTF-8",
    "-Xfuture",
    "-Xfatal-warnings",
    "-Xlint",
    "-Ywarn-dead-code",
    "-Ywarn-adapted-args"
  )
)

**Comment by joost-de-vries** [comment]
This was fixed in [webjars-locator-core](https://github.com/webjars/webjars-locator-core/issues/14) I think.
