### ISSUE TITLE
sbt-web 1.4.0 does not work with sbt-rjs

### ISSUE THREAD

**Issue by codeape** [sbt/sbt-web#147]
The syncMappings method signature has changed with the new cacheName argument with lead to a NoSuchMethodError when using sbt-rjs with sbt-web 1.4.0.

https://github.com/sbt/sbt-rjs/issues/75
https://github.com/sbt/sbt-rjs/issues/66

**Comment by danielnixon** [comment]
Fixed in [my fork](https://github.com/danielnixon/sbt-rjs). Try `addSbtPlugin("org.danielnixon" % "sbt-rjs" % "1.0.9")`.

**Comment by mkurz** [comment]
@danielnixon A pull request would be welcome ;-)

**Comment by danielnixon** [comment]
Here's one from eight months ago. https://github.com/sbt/sbt-rjs/pull/67

**Comment by benmccann** [comment]
This is being tracked in the sbt-rjs repo
