### ISSUE TITLE
Detect production mode

### ISSUE THREAD

**Issue by DGolubets** [sbt/sbt-web#163]
I need to detect dev\production mode in my source generator to enable\disable optimizations.
But I can't find a reliable way of doing it.
Any suggestions?

**Comment by danielnixon** [comment]
You could take a look at how sbt-web-scalajs does it.

https://github.com/vmunier/sbt-web-scalajs/blob/master/src/main/scala/webscalajs/WebScalaJS.scala#L107-L109

**Comment by DGolubets** [comment]
Thanks!
