### ISSUE TITLE
How to change output path in JAR?

### ISSUE THREAD

**Issue by sebrichards** [sbt/sbt-web#167]
Is there a way to change the packaged location of assets in my JAR - i.e. not at `META-INF/resources/webjars/module/version/`?

I've gone through `SbtWeb.scala` and tried all sorts of things (e.g. `directWebModules` and `internalWebModules`), but I just can't work it out.

When I run `package`, I'd like to go from this:
```
+ org
--+ test
----+ Main.class
+ META-INF
--+ resources
----+ webjars
------+ <project name>
--------+ <project version>
----------+ output.min.js
```

...to this:
```
+ org
--+ test
----+ Main.class
+ assets
--+ output.min.js
```

Can anyone advise?

**Comment by marcospereira** [comment]
Hey @sebrichards,

Our [forums](https://discuss.lightbend.com/) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
