### ISSUE TITLE
Memory leak when switching branches, testing and reloading

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-web#170]
We're encountering an actor system leak in the Akka build when switching branches, reloading and testing. The memory dump suggests this might be an sbt-web issue, though we haven't narrowed it down entirely yet. I checked and the revisions with which the problem was reproduced both (transitively) depend on sbt-web 1.4.4.

More details at https://github.com/akka/akka/issues/26737

**Comment by marcospereira** [comment]
If it is an actor system leak in sbt-web, https://github.com/sbt/sbt-web/pull/169 will for sure fix it.

**Comment by mkurz** [comment]
#169 was merged long time ago, there is no akka anymore. Will release sbt-web 1.5.0 soon.
