### ISSUE TITLE
Migrate repository away from travis-ci.org

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-web#180]
travis-ci.org will be shutdown on Dec 31st 2020. 

A new CI environment will be required. There are several options:

1. travis-ci.com:  Travis recommends migrating the jobs to travis-ci.com. Go to https://travis-ci.com/organizations/sbt/migrate to perform the migration(requires login + permissions). The migration operation requires certain permissions in both travis and github over the repository to be migrated. Also, when migrating, some branch protection rules may be lost so extra work to recover that is required. More info and details on https://docs.travis-ci.com/user/migrate/open-source-repository-migration/
2. GitHub Actions
3. Circle CI
4. others...

**Comment by mkurz** [comment]
Fixed by #194
