### ISSUE TITLE
issue with downloading sbt-web from maven central

### ISSUE THREAD

**Issue by pjfanning** [sbt/sbt-web#214]
See https://github.com/apache/incubator-pekko/issues/660#issuecomment-1728038928

Is it possible that there is an issue with https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt and/or https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml?

Would it be possible to publish to https://repo1.maven.org/maven2/com/typesafe/sbt/ ?

**Comment by pjfanning** [comment]
The issue seems to have been a bad entry in a local cache. I'll close this but I must admit I find it easier to work with https://repo1.maven.org/maven2 because its easier to look at its contents in a browser.

**Comment by mkurz** [comment]
There is a newer release already, 1.5.1, and it's hosted on maven central: https://repo1.maven.org/maven2/com/github/sbt/sbt-web_2.12_1.0/1.5.1/
