### ISSUE TITLE
Add support for Grunt

### ISSUE THREAD

**Issue by Mogztter** [sbt/sbt-web#27]
> @Mogztter It'd be great to file an issue at https://github.com/sbt/sbt-web#sbt-web regarding Grunt. The intention is to ultimately support Grunt for those that choose to use it. We're thinking that you should be able to execute Grunt tasks from sbt so that a Grunt build can be integrated into Play's.

See https://github.com/playframework/playframework/pull/2468#issuecomment-37493623

**Comment by jroper** [comment]
This isn't an sbt-web issue, if someone wants to provide an sbt-grunt that integrates with sbt-web then that's fine but sbt-web itself doesn't need to be modified for sbt-grunt.

If you're using Play Framework, then I would recommend not using sbt-web at all if you're using grunt, instead, just use grunt as shown here:

https://www.playframework.com/documentation/2.6.x/SBTCookbook
