### ISSUE TITLE
Comparing sbt-web with grunt for SPAs

### ISSUE THREAD

**Issue by diwa-zz** [sbt/sbt-web#29]
```
This is more of an observation than an issue.
```

I am starting development on a new SaaS product and the chosen stack is  angular front-end + play rest backend. This seems to be an increasingly popular choice.

Initially I wanted to use grunt for the front-end but am now intrigued by the promise of sbt-web as I would also like to keep my development stack simple and integrated. 
However I would like to retain all the development productivity and runtime efficiency that a grunt based solution would offer. 

To compare the solutions, I took the list of [popular grunt plugins](http://gruntjs.com/plugins) and tried to check the equivalent solution in sbt-web/play

| Grunt | Description | sbt-web |
| --- | --- | --- |
| [jshint](https://npmjs.org/package/grunt-contrib-jshint) | Validate files with JsHint | [sbt-jshint](https://github.com/sbt/sbt-jshint) |
| [watch](https://www.npmjs.org/package/grunt-contrib-watch) | Run predefined tasks whenever watched file patterns are added, changed or deleted | sbt + [Play auto refresh](https://github.com/jamesward/play-auto-refresh) |
| [uglify](https://www.npmjs.org/package/grunt-contrib-uglify) | Minify files with UglifyJs | [sbt-uglify](https://github.com/sbt/sbt-uglify), [sbt-rjs](https://github.com/sbt/sbt-rjs) |
| [clean](https://www.npmjs.org/package/grunt-contrib-clean) | Clean files and folders | sbt |
| [copy](https://www.npmjs.org/package/grunt-contrib-copy) | Copy files and folders. | sbt / [sbt-web](https://github.com/sbt/sbt-web/) |
| [concat](https://www.npmjs.org/package/grunt-contrib-concat) | Concatenate files | [sbt-rjs](https://github.com/sbt/sbt-rjs) |
| [cssmin](https://www.npmjs.org/package/grunt-contrib-cssmin) | Compress Css files. | [sbt-less](https://github.com/sbt/sbt-less) - only for less files |
| [connect](https://www.npmjs.org/package/grunt-contrib-connect) | Start a connect web server. | N.A |
| [karma](https://www.npmjs.org/package/grunt-karma) | karma test runner | - |
| [less](https://www.npmjs.org/package/grunt-contrib-less) | Compile Less files to Css. | [sbt-less](https://github.com/sbt/sbt-less) |
| [coffee](https://www.npmjs.org/package/grunt-contrib-coffee) | Compile Coffeescript files to Javascript | [sbt-coffeescript](https://github.com/sbt/sbt-coffeescript) |
| [concurrent](https://www.npmjs.org/package/grunt-concurrent) | Run grunt tasks concurrently | sbt |
| [imagemin](https://www.npmjs.org/package/grunt-contrib-imagemin) | Minify PNG, JPEG and GIF images | - |
| [compass](https://www.npmjs.org/package/grunt-contrib-compass) | Compile sass to Css using Compass | - |
| [usemin](https://www.npmjs.org/package/grunt-usemin) | Replaces references to non-optimized scripts or stylesheets into a set of HTML files [or any templates/views] | [sbt-rjs](https://github.com/sbt/sbt-rjs) |
| [htmlmin](https://www.npmjs.org/package/grunt-contrib-htmlmin) | Minify HTML | - |
| [requirejs](https://www.npmjs.org/package/grunt-contrib-requirejs) | Optimize RequireJs projects using r.js. | [sbt-rjs](https://github.com/sbt/sbt-rjs) |
| [rev](https://www.npmjs.org/package/grunt-rev) | static file asset revisioning through content hashing | [sbt-digest](https://github.com/sbt/sbt-digest) |
| [autoprefixr](https://www.npmjs.org/package/grunt-autoprefixer) | Parse CSS and add vendor-prefixed CSS properties using the Can I Use database | - |
| [shell](https://www.npmjs.org/package/grunt-shell) | Run Shell Commands | sbt |
| [svgmin](https://www.npmjs.org/package/grunt-svgmin) | Minify SVG | - |

In addition, the following is my subjective selection of items which are a little lower in the list (sorted by popularity)

| Grunt | Description | sbt-web |
| --- | --- | --- |
| [newer](https://www.npmjs.org/package/grunt-newer) | Run Grunt tasks with only those source files modified since the last successful run | sbt / [sbt-web](https://github.com/sbt/sbt-web/) |
| [mocha](https://www.npmjs.org/package/grunt-mocha-test) | Grunt task for running client-side Mocha specs in PhantomJs | [sbt-mocha-plugin](https://github.com/sbt/sbt-mocha-plugin) |
| [jasmine](https://www.npmjs.org/package/grunt-contrib-jasmine) | Run jasmine specs headlessly through PhantomJs | - |
| [angular-templates](https://www.npmjs.org/package/grunt-angular-templates) | Grunt build task to concatenate & register your AngularJs templates in the $templateCache | - |
| [protractor-runner](https://www.npmjs.org/package/grunt-protractor-runner) | A Grunt plugin for running protractor runner. | - |
| [ngmin](https://www.npmjs.org/package/grunt-ngmin) | Grunt task for minifying AngularJS projects | - |

I am pleasantly surprised with the coverage present already. I understand that the priority is to have feature-parity with Play 2.2 asset capabilities but it will be great if we tick the missing boxes over time (probably by the community)

It will be good if we can have a documentation page - `sbt-web for grunt users`

**Comment by laguiz** [comment]
Frontend tooling becomes more and more common these days. For example **Gulp** is popular these days and I hear a lot of good feedbacks. I wonder if sbt-web will be able to continue to catch up with these kinds of ecosystems.

IMO an sbt gulp plugin like https://github.com/hedefalk/sbt-gulp-task that play transparently with other sbt-web plugins would be awesome. I still have to give it a try.

@Warry @huntc @others After 6 months what do you guys think? Some minds changed?

**Comment by jroper** [comment]
Closing because there's no actual issue in this.
