### ISSUE TITLE
Add sbt-jasmine

### ISSUE THREAD

**Issue by magro** [sbt/sbt-web#45]
For angular.js apps it would be great to have an sbt-jasmine plugin. Are there plans to add this?

**Comment by ilanbiala** [comment]
@huntc @emmenko @magro there's https://github.com/joescii/sbt-jasmine-plugin and https://github.com/guardian/sbt-jasmine-plugin. Can we just pull in and fix up one of them to to make it available to the community? Jasmine is the primary test runner for AngularJS, which makes it hard to test AngularJS+Scala apps properly.
