### ISSUE TITLE
Exchange information between modules

### ISSUE THREAD

**Issue by akkie** [sbt/sbt-web#49]
I have a use case where the `rjs` module needs information from the `digest` module.

For RequireJS it isn't necessary to pack all modules into one file. In my app as example I use lazy loading for some modules. The problem is now that RequireJS isn't aware of the files created with the `digest` module and it ends up loading the non fingerprinted files.

If the `rjs` module knows the fingerprinted files, it could override the paths config with this files.

Original config:

``` javascript
require.config({
    paths: {
        'jquery': 'lib/jquery-1.11.1'
    }
});
```

Overriden config:

``` javascript
require.config({
    paths: {
        'jquery': 'lib/b028a81918e6cdde3dac41bfa72cf40b-jquery-1.11.1',
        'app/main': 'app/58a15b92be05e9baa3bd9d2ac3b378f7-main',
        ...
    }
});
```

Maybe this can be done with a preprocessor phase. So in this phase the `diggest` module creates a map for already existing files. Now this map is available to other modules so the `rjs` module could rewrite the RequireJS config based on this map.

In the pipeline phase the `rjs` module can do its normal job and the `diggest` module should determine if new files were created by another module and then merge the existing with the created files. At the end it should create the fingerprinted files.

So a `build.sbt` could be defined as follow:

```
preprocessorStages := Seq(digest, rjs)

pipelineStages := Seq(rjs, digest, gzip)
```

What do you you think? Maybe there are other methods to solve this problem.

**Comment by neilchaudhuri** [comment]
Was there any resolution here? If not, what is the workaround? Or is it a choice between RJS and access to digests?
