### ISSUE TITLE
Changes to static files trigger RELOAD

### ISSUE THREAD

**Issue by magro** [sbt/sbt-web#59]
With a play 2.2 application it was possible to change a static file (in `public/`) and see the changes (after F5 or s.th. similar) _without_ a reload of the application. Static files might be e.g. templates/partials of an angular.js application or regular js files (in public).

With 2.3 / sbt-web this is no longer the case - changing a static file triggers a reload of the application.

To reproduce this:
- check out the [angular-seed-play](https://github.com/typesafehub/angular-seed-play) app
- `run` the app
- open [http://localhost:9000/#/view2](http://localhost:9000/#/view2)
- change `public/partials/partial2.html`
- in the browser press F5

Now the console shows that another `--- (RELOAD) ---` was done. This was not the case with play 2.2.1 (to be sure I also checked this with a previous version of angular-seed-play).

Although play apps _should_ reload fast, this is not always the case (or possible). Even if reload takes only 5 or 10 seconds this is rather annoying when working on frontend stuff.

Is it possible to change this, so that static files do not trigger an application reload?

**Comment by michaelahlers** [comment]
I'm running into this with Play 2.4. Anyone else having a similar issue?
