### ISSUE TITLE
Integrating with Spray+sbt-revolver workflow

### ISSUE THREAD

**Issue by stanch** [sbt/sbt-web#91]
Hi,

What’s the best way to integrate _sbt-web_ with _Spray_ and _sbt-revolver_? I have enabled _sbt-web_ with `enablePlugins(SbtWeb)`. The project compiles, however I’m not sure about two things:
- The `~re-start` command from _sbt-revolver_ does not trigger asset (re)compilation. The latter runs only if I touch `show web-assets:assets` explicitly from the _sbt_ console. How do I set this up?
- The processed assets are put into `target/web/public/main`. Should I serve them from there in production, or they are meant to be packaged in some way?

Nick

**Comment by MasseGuillaume** [comment]
I had to add `(fullClasspath in Runtime) += (WebKeys.public in Assets).value`
