### ISSUE TITLE
sbt package will ignore sbt-web

### ISSUE THREAD

**Issue by monzonj** [sbt/sbt-web#92]
Typing 'sbt package' or 'sbt publish', for what it matters, in a fresh Activator 'play-scala' application (or any application) will ignore the assets and the jar won't be generated. Only a play project can generate this jar typing 'dist'

The documentation talks about `web-assets:package`, that doesn't exist.

Regards,

**Comment by MasseGuillaume** [comment]
You can also use `unmanagedResourceDirectories in Compile += (WebKeys.public in Assets).value`. This will include assets in the package and at runtime.
