### ISSUE TITLE
How to use sbt-web to extract some files from a WebJars dependency to a custom output directory ?

### ISSUE THREAD

**Issue by olivergg** [sbt/sbt-web#95]
I'm writing an experimental mobile application with scala.js and the Ionic framework (see https://github.com/olivergg/scalajs-ionic-starttabs).
My project currently depends on the ionic webjar for the javascript dependencies (using jsDependencies, an sbt key defined by scala.js). Thanks to scala.js, the javascript dependencies are automatically copied. I would like to do the same thing for the other files (fonts, css, etc.).

I've tried the following (as documented in the sbt-web homepage)

``` scala
// root is the root project defined in the build.sbt
root.enablePlugins(SbtWeb)

 libraryDependencies ++= Seq(
    // ...
    "org.webjars" % "ionic" % "1.0.0-beta.13"
)

val myPipelineTask = taskKey[Pipeline.Stage]("Some pipeline task")

myPipelineTask := {
    identity
}
pipelineStages := Seq(myPipelineTask)
```

but I don't know what should I do from here....

Thanks.

**Comment by ochrons** [comment]
Here is one way to solve this in a dirty hackish way.

https://github.com/ochrons/scalajs-spa-tutorial/blob/master/project/build.scala#L99-L114

```scala
val copyWebJarResources = TaskKey[Unit]("Copy resources from WebJars")

      copyWebJarResources          := {
        // copy the compiled CSS
        val s = streams.value
        s.log("Copying webjar resources")
        val compiledCss = webTarget.value / "less" / "main" / "stylesheets"
        val targetDir = (classDirectory in Compile).value / "web"
        IO.createDirectory(targetDir / "stylesheets")
        IO.copyDirectory(compiledCss, targetDir / "stylesheets")
        // copy font-awesome fonts from WebJar
        val fonts = (webModuleDirectory in Assets).value / "webjars" / "lib" / "font-awesome" / "fonts"
        IO.createDirectory(targetDir / "fonts")
        IO.copyDirectory(fonts, targetDir / "fonts")
      },
      // run the copy after compile/assets but before managed resources
      copyWebJarResources <<= copyWebJarResources dependsOn (compile in Compile, assets in Compile),
      managedResources in Compile <<= (managedResources in Compile) dependsOn copyWebJarResources
```

Would love to see proper support for targeted WebJar extraction in the plugin itself. There more than Play out there :)

**Comment by olivergg** [comment]
@ochrons  Thanks.

**Comment by olivergg** [comment]
@ochrons I think <<= is deprecated and should be avoided in recent version of sbt (0.13.x). 

Since copyWebJarResources must be run after compile/assets, one should put the following at the top of the copyWebJarResources definition : 

```
(compile in Compile).value
(assets in Compile).value
```

The same way it depends on the streams task with streams.value.

What do you think ?

**Comment by ngbinh** [comment]
You can also use these for references: https://github.com/widok/widok/blob/master/project/Build.scala#L34-L101
