### ISSUE TITLE
Update version of scala to 2.11

### ISSUE THREAD

**Issue by bdmstyle** [sbt/sbt-web#96]
needs update scala to scala 2.11 to support projects using java8 default methods.

**Comment by sam** [comment]
@pvlugter This means you can't write custom SBT Tasks using Scala 2.11.x though right?

If you've written your own plugins, database migration for example, so you could run `set migrate`, then the fact that none of the Play plugins are published for 2.11.x means your own SBT tasks are stuck on 2.10.x.

Have I got that right?
